/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yg.inventory.data.server;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;

import java.util.function.Supplier;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.sun.net.httpserver.HttpServer;

public class Main_UnitTest {
    Supplier<Main> factoryBackup;

    final Main subject = spy(new Main());

    @BeforeEach
    void setup() {
        factoryBackup = Main.factory;
    }

    @AfterEach
    void restore() {
        Main.factory = factoryBackup;
    }

    @Test
    void factory() {
        // Execute
        Main result = Main.factory.get();

        // Verify
        assertNotNull(result);
    }

    @Test
    void build() throws Exception {
        // Execute
        HttpServer result = subject.build();

        // Verify
        assertNotNull(result);

    }

    @Test
    void run() throws Exception {
        // Setup
        HttpServer server = mock(HttpServer.class);
        doReturn(server).when(subject).build();

        // Execute
        subject.run();

        // Verify
        verify(server).start();
    }

    @Test
    void main() {
        // Setup
        Main.factory = () -> subject;
        doNothing().when(subject).run();

        // Execute
        Main.main(null);

        // Verify
        verify(subject).run();
    }
}
