---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: innventory-data-deployment
spec:
  selector:
    matchLabels:
      app: innventory-data
  replicas: 1  
  template:
    metadata:
      labels:
        app: innventory-data
    spec:
      containers:
      - name: innventory-data
        image: yuriyg/inventory-data:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: innventory-data-service
spec:
  type: ClusterIP
  selector:
    app: innventory-data
  ports:
  - protocol: TCP
    port: 3702
    targetPort: 3702

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    namespace: development
    name: innventory-data-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /dev/data(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: innventory-data-service
            port:
              number: 3702