---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: statemach-data-deployment
spec:
  selector:
    matchLabels:
      app: statemach-data
  replicas: 1  
  template:
    metadata:
      labels:
        app: statemach-data
    spec:
      containers:
      - name: statemach-data
        image: yuriyg/statemach-data:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DB_ADDRESS
          value: inventory-db
        - name: DB_PORT
          value: "3703"
        - name: DB_NAME
          value: inventory
        - name: DB_USERNAME
          value: admin
        - name: DB_PASSWORD
          value: M9bmiR8iuod9wFHskgFu

---
apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: statemach-data-service
spec:
  type: ClusterIP
  selector:
    app: statemach-data
  ports:
  - protocol: TCP
    port: 3702
    targetPort: 3702

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    namespace: development
    name: statemach-data-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /dev/data(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: statemach-data-service
            port:
              number: 3702
              