/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yg.inventory.data.service;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.function.Supplier;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import io.undertow.Undertow;

public class Service_UnitTest {
    Supplier<Service> factoryBackup;

    final Service subject = spy(new Service());

    @BeforeEach
    void setup() {
        factoryBackup = Service.factory;
    }

    @AfterEach
    void restore() {
        Service.factory = factoryBackup;
    }

    @Test
    void factory() {
        // Execute
        Service result = Service.factory.get();

        // Verify
        assertNotNull(result);
    }

    @Test
    void build() {
        // Execute
        Undertow result = subject.build();

        // Verify
        assertNotNull(result);

    }

    @Test
    void run() {
        // Setup
        Undertow undertow = mock(Undertow.class);
        when(subject.build()).thenReturn(undertow);

        // Execute
        subject.run();

        // Verify
        verify(undertow).start();
    }

    @Test
    void main() {
        // Setup
        Service.factory = () -> subject;
        doNothing().when(subject).run();

        // Execute
        Service.main(null);

        // Verify
        verify(subject).run();
    }
}
