query {
    second(order: {int: ASC}) {
        int
        fk_second_second_one {
            int
            fk_second_second_two_reverse(order: {double: ASC}) {
                int
            }
        }
    }
}
