query {
    first(filter: {fk_first_second: {fk_second_third: {bool: [true, null]}}}, order: {id: ASC}) {
        id
        fk_first_second {
            int
            fk_second_third {
                indx
                bool
            }
        }
    }
}
