query {
    first(
        filter: {
            fk_second_first_reverse: {int: 222},
            fk_third_first_reverse: {bool: false}
        },
        order: {id: ASC}
    ) {
        id
        fk_second_first_reverse(order: {int: ASC}) {
            int
        }
        fk_third_first_reverse(order: {indx: ASC}) {
            indx
            bool
        }
    }
}
