mutation {
    insert_third(third: {
        name: "Name 5",
        indx: 4,
        first: null,
        second: null,
        bool: null,
        time: null
    }) {
        name
        indx
        first
        second
        bool
        time
    }
}
