query {
    __type(name: "second_update") {
        kind
        name
        inputFields {
            name
            type {
                kind
                name
                ofType {
                    kind
                    name
                }
            }
        }
    }
}
