query {
    __type(name: "third_filter") {
        kind
        name
        fields {
            name
            type {
                kind
                name
                ofType {
                    kind
                    name
                }
            }
        }
    }
}
