mutation {
    update_third(
        name: "Name2",
        indx: 1,
        third: {
            first: null,
            second: null,
            bool: null,
            time: null
        }
    ) {
        name
        indx
        first
        second
        bool
        time
    }
}
