mutation {
    update_first(
        id: 2,
        first: {
            second: "${0}",
            third_name: "Name2",
            third_indx: 1,
            fixed: "Fixed 6",
            varying: "Varying 6",
            unlimited: "Unlimited 6",
        }
    ) {
        id
        second
        third_name
        third_indx
        fixed
        varying
        unlimited
    }
}
