mutation {
    upsert_third(
        name: "Name4",
        indx: 4,
        third: {
            time: "${0}"
        }
    ) {
        name
        indx
        first
        second
        bool
        time
    }
}
