mutation {
    upsert_third(
        name: "Name 7",
        indx: 6,
        third: {
            first: 2,
            second: "${0}",
            bool: true,
            time: "${1}"
        }
    ) {
        name
    }
}
