mutation {
    upsert_first(
        id: 4
        first: {
            second: "${0}"
        }
    ) {
        id
        second
        third_name
        third_indx
        fixed
        varying
        unlimited
    }
}
