mutation {
    upsert_third(
        name: "Name2",
        indx: 1,
        third: {
            first: 2,
            second: "${0}",
            bool: true,
            time: "${1}"
        }
    ) {
        bool
    }
}
